apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: guestbook-dev
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/nitinreddy1/argocd_poc.git
    targetRevision: dev
    path: guestbook/overlays/dev
  destination:
    server: https://kubernetes.default.svc
    namespace: dev
  syncPolicy:
    automated: 
      selfHeal: true 
      prune: true
    syncOptions:     
    - CreateNamespace=true 