apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: guestbook-prod
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/nitinreddy1/argocd_poc.git
    targetRevision: main
    path: guestbook/overlays/prod
  destination:
    server: https://kubernetes.default.svc
    namespace: prod
  syncPolicy:
    automated: 
      selfHeal: true 
      prune: true
    syncOptions:     
    - CreateNamespace=true 