apiVersion: apps/v1
kind: Deployment
metadata:
  name: guestbook-ui
spec:
  replicas: 2
  template:
    spec:
      containers:
      - image: gcr.io/heptio-images/ks-guestbook-demo:latest
        name: guestbook-ui
        ports:
        - containerPort: 8090
        - containerPort: 80
          $patch: delete
