apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namePrefix: stage-
namespace: stage
commonLabels:
  variant: stage
bases:
- ../../base
patchesStrategicMerge:
- guestbook-ui.yaml
- guestbook-ui-svc.yaml